AWSTemplateFormatVersion: 2010-09-09
Description: "ECS Cluster Stack"

# -------------------------------------
# Metadata
# -------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Project Configuration"
        Parameters:
          - ProjectName
          - Environment
      - Label:
          default: "ECS Cluster Configuration"
        Parameters:
          - ContainerInsightsEnabled

# -------------------------------------
# Parameters
# -------------------------------------
Parameters:
  ProjectName:
    Description: "Enter the project name. (ex: shun198)"
    Type: String
    Default: shun198
    MinLength: 1
    ConstraintDescription: "ProjectName must be entered."
  Environment:
    Description: "Select the environment name."
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
    ConstraintDescription: "Environment name must be selected."
  ContainerInsightsEnabled:
    Description: "Select whether to enable ECS container insights."
    Type: String
    AllowedValues:
      - disabled
      - enabled
    Default: disabled

# -------------------------------------
# Resources
# -------------------------------------
Resources:
  # -------------------------------------
  # ECS Cluster
  # -------------------------------------
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ProjectName}-${Environment}-cluster
      ClusterSettings:
        - Name: containerInsights
          Value: !Ref ContainerInsightsEnabled
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-cluster
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # -------------------------------------
  # IAM
  # -------------------------------------
  # ECS タスク実行 (起動) 時に必要な IAM ロール
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        # カスタムメトリクス出力用
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        # ECSTaskExecutionRole が使用できるデフォルト権限
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      RoleName: !Sub ECSTaskExecutionRole-${ProjectName}-${Environment}

  ECSTaskExecutionRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ECSTaskExecutionRoleAccess-${ProjectName}-${Environment}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              # ECR リポジトリおよびイメージの情報取得用
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
              - ecr:DescribeImages
              - ecr:GetAuthorizationToken
              - ecr:GetDownloadUrlForLayer
              - ecr:GetLifecyclePolicyPreview
              - ecr:GetLifecyclePolicy
              - ecr:GetRepositoryPolicy
              - ecr:ListTagsForResource
            Resource:
              - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*
          - Effect: Allow
            Action:
              # 環境変数の取得用
              - ssm:GetParameters
              - secretsmanager:GetSecretValue
              - kms:Decrypt
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*
      Roles:
        - Ref: ECSTaskExecutionRole

  # ECS アプリケーション実行に必要な IAM ロール
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        # カスタムメトリクス出力用
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        # CloudWatchEvents との連携用
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceEventsRole
      RoleName: !Sub ECSTaskRole-${ProjectName}-${Environment}

  ECSTaskRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ECSTaskRoleAccess-${ProjectName}-${Environment}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              # EC2 参照
              - ec2:Describe*
              # ELB 参照
              - elasticloadbalancing:Describe*
              # AutoScaling 参照
              - autoscaling:Describe*
              # CloudWatch 参照
              - cloudwatch:ListMetrics
              - cloudwatch:GetMetricStatistics
              - cloudwatch:Describe*
              # CloudWatch アラーム静観処理
              - cloudwatch:DisableAlarmActions
              - cloudwatch:EnableAlarmActions
              # CloudWatch Logs ログ出力
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
              # SES 経由のメール送信
              - ses:SendRawEmail
              - ses:SendEmail
              - ses:GetSendQuota
              # SNS 経由のメッセージ配信
              - sns:Publish
            Resource: "*"
      Roles:
        - Ref: ECSTaskRole

# -------------------------------------
# Outputs
# -------------------------------------
Outputs:
  ECSClusterName:
    Value: !Ref ECSCluster
  ECSTaskExecutionRoleArn:
    Value: !GetAtt ECSTaskExecutionRole.Arn
  ECSTaskRoleArn:
    Value: !GetAtt ECSTaskRole.Arn
