AWSTemplateFormatVersion: 2010-09-09
Description: "CloudFront With S3 OAC Stack"

# -------------------------------------
# Mappings
# -------------------------------------
Mappings:
  DomainsMap:
    Environment:
      dev: dev.shun-practice.com
      stg: stg.shun-practice.com
      prd: shun-practice.com
  CachePolicyIds:
    CachingOptimized:
      Id: 658327ea-f89d-4fab-a63d-7e88639e58f6
    CachingDisabled:
      Id: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
    CachingOptimizedForUncompressedObjects:
      Id: b2884449-e4de-46a7-ac36-70bc7f1ddd6d
    Elemental-MediaPackage:
      Id: 08627262-05a9-4f76-9ded-b50ca2e3a84f
    Amplify:
      Id: 2e54312d-136d-493c-8eb9-b001f22f67d2
  ResponseHeadersPolicyIds:
    CORS-and-SecurityHeadersPolicy:
      Id: e61eb60c-9c35-4d20-a928-2b84e02af89c
    CORS-With-Preflight:
      Id: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
    CORS-with-preflight-and-SecurityHeadersPolicy:
      Id: eaab4381-ed33-4a86-88ca-d9558dc6cd63
    SecurityHeadersPolicy:
      Id: 67f7725c-6f97-4210-82d7-5512b31e9d03
    SimpleCORS:
      Id: 60669652-455b-4ae9-85a4-c4c02393f86c

# -------------------------------------
# Metadata
# -------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    # パラメータの並び順
    ParameterGroups:
      - Label:
          default: "Project Configuration"
        Parameters:
          - ProjectName
          - Environment
      - Label:
          default: "Route 53 Configuration"
        Parameters:
          - HostZoneID
      - Label:
          default: "CloudFront Configuration"
        Parameters:
          - CloudFrontHostZoneID
          - CachePolicy
          - ResponseHeadersPolicy
          - ACMPublicCertificateArn
          - AssetsBucketRegionDomainName
          - AccessLogsBucketRegionDomainName
          - LambdaFunctionArnForUriPathCompletion

# -------------------------------------
# Input parameters
# -------------------------------------
Parameters:
  ProjectName:
    Description: "Enter the project name. (ex: my-project)"
    Type: String
    MinLength: 1
    ConstraintDescription: "ProjectName must be enter."
    Default: my-project
  Environment:
    Description: "Select the environment."
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
    ConstraintDescription: "Environment must be select."
  # 作成済みの Route 53 ホストゾーン ID
  HostZoneID:
    Description: "Enter the Route 53 Hosted Zone ID."
    Type: AWS::Route53::HostedZone::Id
  CloudFrontHostZoneID:
    Description: "Enter the Hosted Zone ID to be used in the CloudFront distribution alias resource record set."
    Type: String
    # CloudFrontディストリビューションにルーティングするエイリアスレコードを作成する時のID
    Default: Z2FDTNDATAQYW2
    AllowedValues:
      - Z2FDTNDATAQYW2
  CachePolicy:
    Description: "Select the CloudFront cache policy."
    Type: String
    Default: CachingOptimized
    AllowedValues:
      - CachingOptimized
      - CachingDisabled
      - CachingOptimizedForUncompressedObjects
      - Elemental-MediaPackage
      - Amplify
  ResponseHeadersPolicy:
    Description: "Select the CloudFront response headers policy."
    Type: String
    Default: SecurityHeadersPolicy
    AllowedValues:
      - CORS-and-SecurityHeadersPolicy
      - CORS-With-Preflight
      - CORS-with-preflight-and-SecurityHeadersPolicy
      - SecurityHeadersPolicy
      - SimpleCORS
  ACMPublicCertificateArn:
    Description: "Enter the ACM Public Certificate ARN for CloudFront in global (us-east-1) region."
    Type: String
  AssetsBucketRegionDomainName:
    Description: "Enter the S3 bucket region domain name for frontend application assets. (ex: example-assets-bucket.s3.ap-northeast-1.amazonaws.com)"
    Type: String
  AccessLogsBucketRegionDomainName:
    Description: "Enter the S3 bucket region domain name for CloudFront access logs. (ex: example-access-logs-bucket.s3.ap-northeast-1.amazonaws.com)"
    Type: String
  LambdaFunctionArnForUriPathCompletion:
    Description: "Enter the Lambda Function ARN for URI path completion."
    Type: String

# -------------------------------------
# Conditions
# -------------------------------------
Conditions:
  IsPrdEnv: !Equals [!Ref Environment, "prd"]

# -------------------------------------
# Resources
# -------------------------------------
Resources:
  # -------------------------------------
  # Route 53
  # -------------------------------------
  CloudFrontAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostZoneID
      Comment: "for cloudfront"
      Name: !FindInMap [DomainsMap, Environment, !Ref Environment]
      Type: A
      AliasTarget:
        # CloudFront 用の HostZoneID
        HostedZoneId: !Ref CloudFrontHostZoneID
        DNSName: !GetAtt AssetsDistribution.DomainName

  # -------------------------------------
  # CloudFront
  # -------------------------------------
  # Distribution
  AssetsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !Ref AssetsBucketRegionDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        Enabled: true
        DefaultRootObject: index.html
        Comment: "S3 Static Website Hosting Distribution"
        # フロントエンドのレンダリングまたはビルド挙動を考慮したパス指定が必要
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            # Next.js Router にて SSR を制御するために index.html に遷移させる
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          CachePolicyId: !FindInMap [CachePolicyIds, !Ref CachePolicy, Id]
          # PRD環境の時はBasic認証なし
          FunctionAssociations:
            - !If
              - IsPrdEnv
              - !Ref AWS::NoValue
              - EventType: viewer-request
                FunctionARN: !Ref CloudFrontFunctionForBasicAuth
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref LambdaFunctionArnForUriPathCompletion
          ResponseHeadersPolicyId:
            !FindInMap [ResponseHeadersPolicyIds, !Ref ResponseHeadersPolicy, Id]
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMPublicCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Aliases:
          - !FindInMap [DomainsMap, Environment, !Ref Environment]
        IPV6Enabled: false
        Logging:
          Bucket: !Ref AccessLogsBucketRegionDomainName
          IncludeCookies: false
          Prefix: cloudfront/
  # OAC
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: "Origin Access Control For S3 Static Website Hosting"
        Name: !Join
          - "-"
          - - !Sub "${ProjectName}-${Environment}-S3OAC"
            - !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId]]]]
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  # Function（Basic認証）
  CloudFrontFunctionForBasicAuth:
    Type: AWS::CloudFront::Function
    Properties:
      AutoPublish: true
      FunctionCode: |-
        function handler(event) {
          var request = event.request;
          var headers = request.headers;

          // echo -n user:pass | base64
          var authString = "Basic YWlmdWw6ODUxNWFm";

          if (
            typeof headers.authorization === "undefined" ||
            headers.authorization.value !== authString
          ) {
            return {
              statusCode: 401,
              statusDescription: "Unauthorized",
              headers: { "www-authenticate": { value: "Basic" } }
            };
          }

          return request;
        }
      FunctionConfig:
        Comment: "This function for Basic Authorization."
        Runtime: cloudfront-js-1.0
      Name: !Sub ${ProjectName}-${Environment}-BasicAuthorization

# -------------------------------------
# Output Parameters
# -------------------------------------
Outputs:
  AssetsDistributionArn:
    Value: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${AssetsDistribution}
  AssetsDistributionID:
    Value: !Ref AssetsDistribution
  AccessURL:
    Value: !Sub
      - "https://${CloudFrontDomainName}"
      - { CloudFrontDomainName: !GetAtt AssetsDistribution.DomainName }