AWSTemplateFormatVersion: 2010-09-09
Description: 'EC2 Instance'

Parameters:
  MyAvailabilityZone:
    Description: Select the AZ
    Type: String
    Default: ap-northeast-1a
    AllowedValues:
      - ap-northeast-1a
      - ap-northeast-1c
  MyInstanceType:
    # Description: Select the EC2 Instance Type
    # Type: String
    # Default: t2.micro
    # AllowedValues:
    #   - t2.micro
    #   - t2.small
    Description: Select the ec2 instance type from SSM
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cfn-pg/INSTANCE_TYPE

Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      # image名が見つからないエラーが発生したらコンソール上のリージョンを確認すること
      ImageId: ami-08c84d37db8aafe00
      InstanceType: !Ref MyInstanceType
      SecurityGroups:
        # 定義したSSHSecurityGroupを参照させる
        - !Ref SSHSecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZone
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DevEC2Instance