AWSTemplateFormatVersion: 2010-09-09
Description: 'CodeStar Connection Stack'

# -------------------------------------
# Input parameters
# -------------------------------------
Parameters:
  GitHubName:
    Description: "GitHub name will be set as the prefix of the environment variable name. (default: shun198)"
    Type: String
    Default: shun198
  ProviderType:
    Type: String
    Default: GitHub
    AllowedValues:
      - GitHub

# -------------------------------------
# Resources
# -------------------------------------
Resources:
  SourceConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: !Sub ${GitHubName}-connection
      ProviderType: !Ref ProviderType

# -------------------------------------
# Output parameters
# -------------------------------------
Outputs:
  SourceConnectionArn:
    Value: !Ref SourceConnection
