AWSTemplateFormatVersion: 2010-09-09
Description: "Chatbot Stack"

# -------------------------------------
# Metadata
# -------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Chatbot Configuration"
        Parameters:
          - ChatbotRoleName
      - Label:
          default: "Slack Configuration"
        Parameters:
          - SlackWorkspaceID
          - SlackChannelIDForCICDPipeline
      - Label:
          default: "SNS Configuration"
        Parameters:
          - CICDPipelineTopicName

# -------------------------------------
# Input Parameters
# -------------------------------------
Parameters:
  ChatbotRoleName:
    Type: String
    Description: "Enter the Chatbot Role name (default: AWSChatbotRole)"
    Default: AWSChatbotRole
  SlackWorkspaceID:
    Type: String
  # CI/CD 関連通知先の Slack Channel ID
  SlackChannelIDForCICDPipeline:
    Type: String
    Description: |-
      Enter the Slack channel ID for individual notifications only in the production environment.
      For other environments (i.e. development or staging),
      enter the Slack channel ID for aggregated notifications for each environment
  # CI/CD 関連通知先 SNS TopicName
  CICDPipelineTopicName:
    Type: String
    Default: cicd-pipeline

# -------------------------------------
# Resources
# -------------------------------------
Resources:
  # -------------------------------------
  # IAM Role
  # -------------------------------------
  # AWS Chatbot による Slack 連携時に必要な IAM ロール
  ChatbotRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ChatbotRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: chatbot.amazonaws.com
            Action: sts:AssumeRole
      Path: /service-linked-role/
      Policies:
        - PolicyName: AWSChatbotNotificationsOnlyAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:Describe*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                Resource:
                  - "*"

  # -------------------------------------
  # Chatbot
  # -------------------------------------
  ChatbotForCICD:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: notice-aws-cicd-pipeline
      IamRoleArn: !GetAtt ChatbotRole.Arn
      LoggingLevel: INFO
      SlackWorkspaceId: !Ref SlackWorkspaceID
      SlackChannelId: !Ref SlackChannelIDForCICDPipeline
      SnsTopicArns:
        - !Sub arn:aws:sns:ap-northeast-1:${AWS::AccountId}:${CICDPipelineTopicName}

