AWSTemplateFormatVersion: 2010-09-09
Description: "SQS Stack For Lambda Function"

# -------------------------------------
# Metadata
# -------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Project Configuration"
        Parameters:
          - ProjectName
          - Environment
      - Label:
          default: "SQS Configuration"
        Parameters:
          - SQSQueueName
          - ECSTaskRoleArn

# -------------------------------------
# Parameters
# -------------------------------------
Parameters:
  ProjectName:
    Description: "Enter the project name (ex: my-project)"
    Type: String
    MinLength: 1
    ConstraintDescription: "ProjectName must be entered"
    Default: my-project
  Environment:
    Description: "Select the environment"
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
    ConstraintDescription: "Environment must be selected"
  SQSQueueName:
    Description: "Enter the upload csv queue name (ex: my-project-dev-upload-csv-sqs.fifo)"
    Type: String
  MessageRetentionPeriod:
    Description: "Enter the time to hold messages as a queue (default: 3600)"
    Type: Number
    Default: 3600
    MinValue: 60
    MaxValue: 1209600
    ConstraintDescription: "MessageRetentionPeriod must be entered between the values 60 - 1209600"
  ECSTaskRoleArn:
    Description: "Enter the ECS Task Role Arn (ex: arn:aws:iam::012345678910:role/xxxxxxxx)"
    Type: String

# -------------------------------------
# Resources
# -------------------------------------
Resources:
  # For SQS
  UploadCSVQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      ContentBasedDeduplication: true
      QueueName: !Ref SQSQueueName
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  # For SQS Access Policy
  UploadCSVQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref ECSTaskRoleArn
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
            Resource: !GetAtt UploadCSVQueue.Arn
      Queues:
        - !Ref UploadCSVQueue

# -------------------------------------
# Outputs
# -------------------------------------
Outputs:
  UploadCSVQueueArn:
    Value: !GetAtt UploadCSVQueue.Arn
  UploadCSVQueueUrl:
    Value: !Ref UploadCSVQueue
