name: Deploy CloudFormation Templates to S3

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches-ignore:
      - "release/**"
      - "doc/**"

env:
  WORKING_DIRECTORY: templates
  REGION_NAME: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Chekcout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed templates
        id: templates
        run: |
          # 変更されたファイルをリストアップして、配列として格納
          templates=$(git diff origin/main --name-only | grep -c ${{ env.WORKING_DIRECTORY }}/)
          echo 'templates=${templates}'' >> $GITHUB_ENV
      # - name: configure aws credentials
      #   if: env.TEMPLATE_CHANGED == 'true'
      #   run: echo 'template changed'
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::XXXXXXXXXXXX:role/github-actions-deploy-s3-bucket
      #     role-session-name: samplerolesession
      #     aws-region: ${{ env.REGION_NAME }}
      - name: Upload to S3
        if: ${{ env.changed_files != '' }}
        run: |
          # ファイルごとにアップロード
          for file in ${{ env.changed_files }}; do
            echo 'file'
          done
        # run: |
        #   # ファイルごとにアップロード
        #   for file in ${{ env.changed_files }}; do
        #     aws s3 cp "$file" "s3://your-bucket-name/$file" --acl public-read
        #   done

