name: Deploy CloudFormation Templates to S3

on:
  workflow_dispatch

env:
  WORKING_DIRECTORY: templates
  REGION_NAME: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Chekcout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed templates
        id: templates
        run: |
          templates=$(git HEAD~1 --name-status | grep ${{ env.WORKING_DIRECTORY }}/ | grep "^M\|^A" | cut -f2)
          echo "templates=$templates" >> $GITHUB_ENV
      # - name: configure aws credentials
      #   if: env.TEMPLATE_CHANGED == 'true'
      #   run: echo 'template changed'
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::XXXXXXXXXXXX:role/github-actions-deploy-s3-bucket
      #     role-session-name: samplerolesession
      #     aws-region: ${{ env.REGION_NAME }}
      # - name: Upload to S3
      #   # if: ${{ env.changed_files != '' }}
      #   run: |
      #     echo ${{ env.templates }}
      #     # ファイルごとにアップロード
      #     for template in ${{ env.templates }}; do
      #       echo $template
      #     done
        # run: |
        #   # ファイルごとにアップロード
        #   for file in ${{ env.changed_files }}; do
        #     aws s3 cp "$file" "s3://your-bucket-name/$file" --acl public-read
        #   done

